# Generated by Django 5.0.6 on 2024-06-14 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_drink_options_alter_food_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_created'], 'verbose_name': 'Product'},
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
