# Generated by Django 5.0.6 on 2024-06-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_name_product_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['data_criada'], 'verbose_name': 'Product'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='data_criada',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='purchase_price',
            new_name='preco_de_compra',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sell_price',
            new_name='preco_de_venda',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity_in_stock',
            new_name='quantidade_em_estoque',
        ),
    ]
