# Generated by Django 5.0.6 on 2024-06-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categoria',
        ),
    ]
