# Generated by Django 5.0.6 on 2024-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantidade_em_estoque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='preco_de_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='preco_de_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
