# Generated by Django 5.0.6 on 2024-06-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_quantidade_em_estoque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
