# Generated by Django 5.0.6 on 2024-06-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_product_categoria_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantidade_em_estoque',
            field=models.IntegerField(),
        ),
    ]
