# Generated by Django 5.0.6 on 2024-06-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_produto_id_sale_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['data_criada'], 'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='produto',
            new_name='produto_id',
        ),
    ]
