# Generated by Django 5.0.6 on 2024-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_quantidade_sale_vendidos_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='lucro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
