# Generated by Django 5.0.6 on 2024-06-18 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_sale_produto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='produto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
